export default {
    ADD_GAME_DATA: 'ADD_GAME_DATA',
    GOTO_NEXT_QUESTION: 'GOTO_NEXT_QUESTION',
    RESET_GAME_STATE: 'RESET_GAME_STATE',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    CHANGE_GAME_TYPE: 'CHANGE_GAME_TYPE',
    SELECT_ARTIST: 'SELECT_ARTIST',
    SELECT_GENRE: 'SELECT_GENRE',
    DECREASE_TIMER: 'DECREASE_TIMER',
    RESET_TIMER: 'RESET_TIMER',
    WAITING_FOR_GAME: 'WAITING_FOR_GAME',
    INGAME: 'INGAME',
    ADD_OPTION_ARTISTS: 'ADD_OPTION_ARTISTS',
    ADD_OPTION_GENRES: 'ADD_OPTION_GENRES'
}