export default {
    ADD_GAME_DATA: 'ADD_GAME_DATA',
    GOTO_NEXT_QUESTION: 'GOTO_NEXT_QUESTION',
    RESET_GAME_STATE: 'RESET_GAME_STATE',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    CHANGE_GAME_TYPE: 'CHANGE_GAME_TYPE',
    SELECT_ARTIST: 'SELECT_ARTIST',
    SELECT_GENRE: 'SELECT_GENRE',
    DECREASE_TIMER: 'DECREASE_TIMER',
    RESET_TIMER: 'RESET_TIMER',
    ADD_OPTION_ARTISTS: 'ADD_OPTION_ARTISTS',
    ADD_OPTION_GENRES: 'ADD_OPTION_GENRES',
    UPDATE_QUESTION_ANSWER: 'UPDATE_QUESTION_ANSWER',
    RESET_QUESTION_ANSWER: 'RESET_QUESTION_ANSWER',
    SET_GAME_RESULTS: 'SET_GAME_RESULTS',
    NEXT_GAME_PHASE: 'NEXT_GAME_PHASE',
    RESET_GAME_PHASE: 'RESET_GAME_PHASE'
}