export default {
    ADD_GAME_DATA: 'ADD_GAME_DATA',
    GOTO_NEXT_QUESTION: 'GOTO_NEXT_QUESTION',
    RESET_GAME_STATE: 'RESET_GAME_STATE',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    ADD_OPTION_DATA: 'ADD_OPTION_DATA',
    CHANGE_GAME_TYPE: 'CHANGE_GAME_TYPE',
    SELECT_ARTIST: 'SELECT_ARTIST',
    SELECT_GENRE: 'SELECT_GENRE'
}